### ISSUE TITLE
Not compatible with current node versions!

### ISSUE THREAD

**Issue by adammmanka** [zapproject/zap-term#8]
This node package is having issues with 10.15.3+ node versions. We need to trouble shoot the packages and figure out how to fix this. Will review

**Comment by adammmanka** [comment]
21330 silly saveTree └── web3@1.0.0-beta.55
21331 warn @babel/plugin-transform-runtime@7.11.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
21332 verbose stack Error: scrypt@6.0.3 install: `node-gyp rebuild`
21332 verbose stack Exit status 1
21332 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
21332 verbose stack     at EventEmitter.emit (events.js:311:20)
21332 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
21332 verbose stack     at ChildProcess.emit (events.js:311:20)
21332 verbose stack     at maybeClose (internal/child_process.js:1021:16)
21332 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
21333 verbose pkgid scrypt@6.0.3
21334 verbose cwd /mnt/c/projects/zap-term
21335 verbose Linux 4.4.0-18362-Microsoft
21336 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
21337 verbose node v12.16.1
21338 verbose npm  v6.13.4
21339 error code ELIFECYCLE
21340 error errno 1
21341 error scrypt@6.0.3 install: `node-gyp rebuild`
21341 error Exit status 1
21342 error Failed at the scrypt@6.0.3 install script.
21342 error This is probably not a problem with npm. There is likely additional logging output above.
21343 verbose exit [ 1, true ]

**Comment by adammmanka** [comment]
Seems to be an error related to https://github.com/ricmoo/scrypt-js/issues/18
